metrics-server:
  replicas: 3
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  nodeSelector:
    karpenter.sh/nodepool: system
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
    effect: "NoSchedule"