apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: add-ons
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |
        repoUrl: 'https://github.com/lindarr915/eks-blueprints-add-ons.git'
        metricsServer:
          enable: true
        argoWorkflows:
          enable: true
        certManager:
          enable: true
        kubeRayOperator:
          enable: true
        kubePrometheusStack:
          enable: true
        externalDns:
          enable: true
          createNamespace: true
          nodeSelector: 
            karpenter.sh/nodepool: system
          tolerations: 
            - key: "CriticalAddonsOnly"
              operator: "Exists"
              effect: "NoSchedule"

    path: chart
    repoURL: https://github.com/lindarr915/eks-blueprints-add-ons.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}


