apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu
spec:
  disruption:
    consolidateAfter: 60m
    consolidationPolicy: WhenEmpty
  limits:
    cpu: 1k
    memory: 1000Gi
    nvidia.com/gpu: 50
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        name: default
        kind: NodeClass
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64"]
      - key: eks.amazonaws.com/instance-category
        operator: In
        values: ["g"]
      - key: eks.amazonaws.com/instance-generation
        operator: Gt
        values: ["5"]
      - key: kubernetes.io/os
        operator: In
        values: ["linux"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand"]
      taints:
      - effect: NoSchedule
        key: ray.io/node-type
        value: worker
      - effect: NoSchedule
        key: nvidia.com/gpu